// Cloudflare Worker entry: the OpenNext-generated Next.js handler plus a
// scheduled handler that runs the cloud fallback checks. Excluded from the
// Next.js TypeScript project; wrangler bundles it.
// @ts-expect-error generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";

type Env = { CRON_SECRET?: string; APP_URL?: string };

type ScheduledController = { scheduledTime: number; cron: string };
type ExecutionContext = { waitUntil(promise: Promise<unknown>): void };

export default {
  fetch: handler.fetch,

  async scheduled(controller: ScheduledController, env: Env, ctx: ExecutionContext) {
    const base = (env.APP_URL ?? "https://pagedog.internal").replace(/\/$/, "");
    const req = new Request(`${base}/api/cron/check`, {
      method: "POST",
      headers: { authorization: `Bearer ${env.CRON_SECRET ?? ""}` },
    });
    ctx.waitUntil(
      handler.fetch(req, env, ctx).then(async (res: Response) => {
        console.log(`cron ${controller.cron} -> ${res.status} ${(await res.text()).slice(0, 200)}`);
      }),
    );
  },
};
